version: '3.8'
services:
  db:
    container_name: ecm-pg
    image: postgres:16.1-alpine3.18
    environment:
      POSTGRES_USER: ecm
      POSTGRES_PASSWORD: Ecm!23456
      POSTGRES_DB: ecm
    ports:
      - "5432:5432"
  pgadmin:
    container_name: ecm-pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
